### PR TITLE
Run on Travis containers, not VMs [WIP]

### PR DESCRIPTION
**Pull request by pnorman**
Follow-up to #449.

This is a WIP to get Travis to run so I can see the failures.

### CODE REVIEW

**Comment by pnorman** [comment]
Node 4 and 7 pass, but 6 fails with

```
  208 passing (7s)
  1 failing
  1) Rendering should render fontset-duplication.mml correctly:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at test/rendering.test.js:94:17
      at test/support/helper.js:102:28
      at Object.parser.onclosetag (test/support/helper.js:82:39)
```

**Comment by pnorman** [comment]
Looks like this was a failure using the *coverage* tests. During the initial tests, it was 1342ms.

Also slow during coverage

```
  jslint
    eslint
      ✓ should have no errors in bin
      ✓ should have no errors in lib (1660ms)
      ✓ should have no errors in test (453ms)
```

My suggestion would be to boost the timeout then open a bug about fontset-duplication.mml being slow

**Comment by nebulon42** [comment]
> Also slow during coverage

That's something I missed. It does not make much sense to include linting in the coverage run, so we should get rid of it if possible.

**Comment by nebulon42** [comment]
Superseded by #459 and #460. Thanks for the initiative!

**Pull request closed without merging**
